--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.5
-- Dumped by pg_dump version 9.6.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: evidence; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA evidence;


--
-- Name: items; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA items;


--
-- Name: network; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA network;


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: actions_sets; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.actions_sets (
    item_id_a integer,
    item_id_b integer,
    mode character varying,
    sources text
);


--
-- Name: collections; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.collections (
    collection_id character varying(20) NOT NULL,
    pubmed_id character varying(20) NOT NULL,
    comment character varying(1000)
);


--
-- Name: fusion_evidence; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.fusion_evidence (
    target_protein_id_a integer NOT NULL,
    target_protein_id_b integer NOT NULL,
    source_protein integer NOT NULL,
    source_species integer NOT NULL,
    transfer_score_c1 smallint NOT NULL,
    transfer_score_c2 smallint NOT NULL,
    fusion_score smallint NOT NULL
);


--
-- Name: items_publications; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.items_publications (
    item_id integer NOT NULL,
    publication_id character varying(20) NOT NULL,
    name_shown character varying(120) NOT NULL,
    paragraph_number smallint NOT NULL,
    sentence_number_in_paragraph smallint NOT NULL,
    start_position integer NOT NULL,
    end_position integer NOT NULL,
    go_id integer
);


--
-- Name: items_sentences_nlp; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.items_sentences_nlp (
    item_id integer NOT NULL,
    publication_id character varying(20) NOT NULL,
    sentence_id integer NOT NULL,
    name_shown character varying(120) NOT NULL,
    sentence_start_position integer,
    sentence_end_position integer,
    sentence_text text
);


--
-- Name: orthgroups_publications; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.orthgroups_publications (
    orthgroup_id integer NOT NULL,
    publication_id character varying(20) NOT NULL
);


--
-- Name: orthgroups_sets; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.orthgroups_sets (
    orthgroup_id integer NOT NULL,
    set_id character varying(60) NOT NULL,
    set_type character(1) NOT NULL
);


--
-- Name: publications; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.publications (
    publication_id character varying(20) NOT NULL,
    publication_date smallint,
    publication_source text,
    linkout_url text,
    authors text,
    title text,
    abstract text
);


--
-- Name: sets; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.sets (
    set_id character varying(60) NOT NULL,
    collection_id character varying(20) NOT NULL,
    title character varying(100),
    comment character varying,
    url character varying
);


--
-- Name: sets_items; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.sets_items (
    set_id character varying(60) NOT NULL,
    item_id integer NOT NULL,
    species_id integer NOT NULL,
    preferred_name character varying(50) NOT NULL,
    set_type character(1) NOT NULL
);


--
-- Name: sets_pubmedrefs; Type: TABLE; Schema: evidence; Owner: -
--

CREATE TABLE evidence.sets_pubmedrefs (
    set_id character varying(60) NOT NULL,
    pubmed_id character varying(20)
);


--
-- Name: genes; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.genes (
    gene_id integer NOT NULL,
    gene_external_id character varying(100) NOT NULL,
    start_position_on_contig integer NOT NULL,
    end_position_on_contig integer NOT NULL,
    protein_size integer NOT NULL
);


--
-- Name: genes_proteins; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.genes_proteins (
    protein_id integer NOT NULL,
    gene_id integer NOT NULL
);


--
-- Name: hierarchical_ogs_proteins; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.hierarchical_ogs_proteins (
    eggnog_id integer,
    species_id integer,
    protein_id integer
);


--
-- Name: orthgroups; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.orthgroups (
    orthgroup_id integer NOT NULL,
    orthgroup_external_id character varying(20) NOT NULL,
    description character varying(1000) NOT NULL,
    protein_count integer NOT NULL,
    species_count smallint NOT NULL
);


--
-- Name: orthgroups_species; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.orthgroups_species (
    orthgroup_id integer NOT NULL,
    species_id integer NOT NULL,
    count integer NOT NULL
);


--
-- Name: proteins; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins (
    protein_id integer NOT NULL,
    protein_external_id character varying(50) NOT NULL,
    species_id integer NOT NULL,
    protein_checksum character varying(16) NOT NULL,
    protein_size integer NOT NULL,
    annotation character varying(600) NOT NULL,
    preferred_name character varying(50) NOT NULL,
    annotation_word_vectors tsvector
);


--
-- Name: proteins_hierarchical_ogs; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_hierarchical_ogs (
    protein_id integer NOT NULL,
    level_id integer NOT NULL,
    eggnog_id integer NOT NULL
);


--
-- Name: proteins_imagematches; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_imagematches (
    protein_id integer,
    image_id character varying(60),
    identity numeric,
    source character varying(10),
    start_position_on_protein integer,
    end_position_on_protein integer,
    annotation character varying(50),
    linkout_url character varying(200)
);


--
-- Name: proteins_linkouts; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_linkouts (
    protein_id integer NOT NULL,
    linkout_type character varying(15),
    is_primary_linkout boolean,
    linkout_url character varying(150)
);


--
-- Name: proteins_names; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_names (
    protein_name character varying(100) NOT NULL,
    protein_id integer NOT NULL,
    species_id integer NOT NULL,
    source character varying(100) NOT NULL,
    is_preferred_name boolean
);


--
-- Name: proteins_orthgroups; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_orthgroups (
    orthgroup_id integer NOT NULL,
    protein_id integer NOT NULL,
    protein_external_id character varying(50) NOT NULL,
    species_id integer NOT NULL,
    start_position integer NOT NULL,
    end_position integer NOT NULL,
    preferred_name character varying(50) NOT NULL,
    protein_annotation character varying(100) NOT NULL,
    preferred_linkout_url character varying(150)
);


--
-- Name: proteins_sequences; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_sequences (
    protein_id integer NOT NULL,
    sequence text NOT NULL
);


--
-- Name: proteins_smartlinkouts; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.proteins_smartlinkouts (
    protein_id integer NOT NULL,
    protein_size integer NOT NULL,
    smart_url character varying(2000) NOT NULL
);


--
-- Name: runs; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.runs (
    run_id integer NOT NULL,
    species_id integer NOT NULL,
    contig_id character varying(50) NOT NULL
);


--
-- Name: runs_genes_proteins; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.runs_genes_proteins (
    run_id integer NOT NULL,
    gene_id integer NOT NULL,
    protein_id integer NOT NULL,
    start_position_on_contig integer NOT NULL,
    end_position_on_contig integer NOT NULL,
    preferred_name character varying(50) NOT NULL,
    annotation character varying(100) NOT NULL
);


--
-- Name: runs_orthgroups; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.runs_orthgroups (
    run_id integer NOT NULL,
    orthgroup_id integer NOT NULL
);


--
-- Name: species; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.species (
    species_id integer NOT NULL,
    official_name character varying(100) NOT NULL,
    compact_name character varying(100) NOT NULL,
    kingdom character varying(15) NOT NULL,
    type character varying(10) NOT NULL,
    protein_count integer
);


--
-- Name: species_names; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.species_names (
    species_id integer,
    species_name character varying,
    official_name character varying,
    is_string_species boolean,
    kind character varying
);


--
-- Name: species_nodes; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.species_nodes (
    species_id integer NOT NULL,
    species_name character varying NOT NULL,
    "position" integer NOT NULL,
    size integer NOT NULL
);


--
-- Name: species_to_levels; Type: TABLE; Schema: items; Owner: -
--

CREATE TABLE items.species_to_levels (
    species_id integer NOT NULL,
    level_ids integer[] NOT NULL
);


--
-- Name: actions; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.actions (
    item_id_a integer,
    item_id_b integer,
    mode character varying,
    action character varying,
    is_directional boolean,
    a_is_acting boolean,
    score smallint
);


--
-- Name: best_combined_scores_orthgroups; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.best_combined_scores_orthgroups (
    orthgroup_id integer NOT NULL,
    best_score integer NOT NULL
);


--
-- Name: best_combined_scores_proteins; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.best_combined_scores_proteins (
    protein_id integer NOT NULL,
    best_score integer NOT NULL
);


--
-- Name: hierarchical_ogs_transfer_reports; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.hierarchical_ogs_transfer_reports (
    score_id smallint,
    eggnog_id_a integer,
    eggnog_id_b integer,
    species_id integer,
    protein_id_a integer,
    protein_id_b integer
);


--
-- Name: node_node_links; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.node_node_links (
    node_id_a integer,
    node_type_b integer,
    node_id_b integer,
    combined_score smallint,
    evidence_scores smallint[]
);


--
-- Name: score_types; Type: TABLE; Schema: network; Owner: -
--

CREATE TABLE network.score_types (
    score_id smallint NOT NULL,
    score_type character varying(35) NOT NULL
);


--
-- Name: pi_actions_sets_items_new; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_actions_sets_items_new ON evidence.actions_sets USING btree (item_id_a, item_id_b);

ALTER TABLE evidence.actions_sets CLUSTER ON pi_actions_sets_items_new;


--
-- Name: pi_collections; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_collections ON evidence.collections USING btree (collection_id);

ALTER TABLE evidence.collections CLUSTER ON pi_collections;


--
-- Name: pi_fusion_evidence; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_fusion_evidence ON evidence.fusion_evidence USING btree (target_protein_id_a);

ALTER TABLE evidence.fusion_evidence CLUSTER ON pi_fusion_evidence;


--
-- Name: pi_items_publications_item_id_publication_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_items_publications_item_id_publication_id ON evidence.items_publications USING btree (item_id, publication_id);


--
-- Name: pi_items_sentences_item_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_items_sentences_item_id ON evidence.items_sentences_nlp USING btree (item_id);

ALTER TABLE evidence.items_sentences_nlp CLUSTER ON pi_items_sentences_item_id;


--
-- Name: pi_orthgroups_publications_orthgroup_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_orthgroups_publications_orthgroup_id ON evidence.orthgroups_publications USING btree (orthgroup_id);

ALTER TABLE evidence.orthgroups_publications CLUSTER ON pi_orthgroups_publications_orthgroup_id;


--
-- Name: pi_orthgroups_sets_orthgroup_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_orthgroups_sets_orthgroup_id ON evidence.orthgroups_sets USING btree (orthgroup_id);

ALTER TABLE evidence.orthgroups_sets CLUSTER ON pi_orthgroups_sets_orthgroup_id;


--
-- Name: pi_publications_publication_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_publications_publication_id ON evidence.publications USING btree (publication_id);

ALTER TABLE evidence.publications CLUSTER ON pi_publications_publication_id;


--
-- Name: pi_sets_pubmedrefs; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_sets_pubmedrefs ON evidence.sets_pubmedrefs USING btree (set_id);


--
-- Name: pi_sets_sets; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX pi_sets_sets ON evidence.sets USING btree (set_id);

ALTER TABLE evidence.sets CLUSTER ON pi_sets_sets;


--
-- Name: si_items_publications_publication_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_items_publications_publication_id ON evidence.items_publications USING btree (publication_id);


--
-- Name: si_items_sentences_publication_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_items_sentences_publication_id ON evidence.items_sentences_nlp USING btree (publication_id);


--
-- Name: si_orthgroups_sets_set_id; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_orthgroups_sets_set_id ON evidence.orthgroups_sets USING btree (set_id);


--
-- Name: si_sets_collections; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_sets_collections ON evidence.sets USING btree (collection_id);


--
-- Name: si_sets_items_1; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_sets_items_1 ON evidence.sets_items USING btree (set_id, item_id);

ALTER TABLE evidence.sets_items CLUSTER ON si_sets_items_1;


--
-- Name: si_sets_items_2; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_sets_items_2 ON evidence.sets_items USING btree (item_id, set_id);


--
-- Name: si_sets_items_3; Type: INDEX; Schema: evidence; Owner: -
--

CREATE INDEX si_sets_items_3 ON evidence.sets_items USING btree (item_id, set_type, set_id);


--
-- Name: ii_protein_imagematches; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX ii_protein_imagematches ON items.proteins_imagematches USING btree (image_id);


--
-- Name: pi_genes_geneid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_genes_geneid ON items.genes USING btree (gene_id);

ALTER TABLE items.genes CLUSTER ON pi_genes_geneid;


--
-- Name: pi_genes_proteins_combined; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_genes_proteins_combined ON items.genes_proteins USING btree (gene_id, protein_id);


--
-- Name: pi_genes_proteins_proteinid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_genes_proteins_proteinid ON items.genes_proteins USING btree (protein_id);

ALTER TABLE items.genes_proteins CLUSTER ON pi_genes_proteins_proteinid;


--
-- Name: pi_hierarchical_ogs_proteins_eggnog_id_species_id; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_hierarchical_ogs_proteins_eggnog_id_species_id ON items.hierarchical_ogs_proteins USING btree (eggnog_id, species_id);

ALTER TABLE items.hierarchical_ogs_proteins CLUSTER ON pi_hierarchical_ogs_proteins_eggnog_id_species_id;


--
-- Name: pi_orthgroups_orthgroupid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_orthgroups_orthgroupid ON items.orthgroups USING btree (orthgroup_id);

ALTER TABLE items.orthgroups CLUSTER ON pi_orthgroups_orthgroupid;


--
-- Name: pi_orthgroups_species_orthgroupid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_orthgroups_species_orthgroupid ON items.orthgroups_species USING btree (orthgroup_id);

ALTER TABLE items.orthgroups_species CLUSTER ON pi_orthgroups_species_orthgroupid;


--
-- Name: pi_protein_imagematches; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_protein_imagematches ON items.proteins_imagematches USING btree (protein_id);

ALTER TABLE items.proteins_imagematches CLUSTER ON pi_protein_imagematches;


--
-- Name: pi_proteins_hierarchical_ogs_protein_id_level_id; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_hierarchical_ogs_protein_id_level_id ON items.proteins_hierarchical_ogs USING btree (protein_id, level_id);

ALTER TABLE items.proteins_hierarchical_ogs CLUSTER ON pi_proteins_hierarchical_ogs_protein_id_level_id;


--
-- Name: pi_proteins_linkouts_proteinid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_linkouts_proteinid ON items.proteins_linkouts USING btree (protein_id);

ALTER TABLE items.proteins_linkouts CLUSTER ON pi_proteins_linkouts_proteinid;


--
-- Name: pi_proteins_names_name; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_names_name ON items.proteins_names USING btree (protein_name);

ALTER TABLE items.proteins_names CLUSTER ON pi_proteins_names_name;


--
-- Name: pi_proteins_orthgroups_orthgroupid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_orthgroups_orthgroupid ON items.proteins_orthgroups USING btree (orthgroup_id);

ALTER TABLE items.proteins_orthgroups CLUSTER ON pi_proteins_orthgroups_orthgroupid;


--
-- Name: pi_proteins_proteinid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_proteinid ON items.proteins USING btree (protein_id);

ALTER TABLE items.proteins CLUSTER ON pi_proteins_proteinid;


--
-- Name: pi_proteins_sequences; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_sequences ON items.proteins_sequences USING btree (protein_id);

ALTER TABLE items.proteins_sequences CLUSTER ON pi_proteins_sequences;


--
-- Name: pi_proteins_smartlinkouts_proteinid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_proteins_smartlinkouts_proteinid ON items.proteins_smartlinkouts USING btree (protein_id);

ALTER TABLE items.proteins_smartlinkouts CLUSTER ON pi_proteins_smartlinkouts_proteinid;


--
-- Name: pi_runs_genespr_runid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_runs_genespr_runid ON items.runs_genes_proteins USING btree (run_id);

ALTER TABLE items.runs_genes_proteins CLUSTER ON pi_runs_genespr_runid;


--
-- Name: pi_runs_runid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_runs_runid ON items.runs USING btree (run_id);

ALTER TABLE items.runs CLUSTER ON pi_runs_runid;


--
-- Name: pi_species_names; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_species_names ON items.species_names USING btree (upper((species_name)::text));

ALTER TABLE items.species_names CLUSTER ON pi_species_names;


--
-- Name: pi_species_nodes; Type: INDEX; Schema: items; Owner: -
--

CREATE UNIQUE INDEX pi_species_nodes ON items.species_nodes USING btree (species_id);

ALTER TABLE items.species_nodes CLUSTER ON pi_species_nodes;


--
-- Name: pi_species_speciesid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_species_speciesid ON items.species USING btree (species_id);

ALTER TABLE items.species CLUSTER ON pi_species_speciesid;


--
-- Name: pi_species_to_levels_species_id; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX pi_species_to_levels_species_id ON items.species_to_levels USING btree (species_id);

ALTER TABLE items.species_to_levels CLUSTER ON pi_species_to_levels_species_id;


--
-- Name: proteins_annotation_index; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX proteins_annotation_index ON items.proteins USING gist (annotation_word_vectors);


--
-- Name: si_genes_combined; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_genes_combined ON items.genes USING btree (gene_external_id, gene_id);


--
-- Name: si_orthgroups_combined; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_orthgroups_combined ON items.orthgroups USING btree (orthgroup_external_id, orthgroup_id);


--
-- Name: si_proteins_checksum; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_checksum ON items.proteins USING btree (protein_checksum);


--
-- Name: si_proteins_combined; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_combined ON items.proteins USING btree (protein_external_id, protein_id);


--
-- Name: si_proteins_names_protein; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_names_protein ON items.proteins_names USING btree (protein_id);


--
-- Name: si_proteins_names_protein_plain; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_names_protein_plain ON items.proteins_names USING btree (protein_name varchar_pattern_ops);


--
-- Name: si_proteins_names_upper_name; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_names_upper_name ON items.proteins_names USING btree (upper((protein_name)::text));


--
-- Name: si_proteins_orthgroups_combined; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_orthgroups_combined ON items.proteins_orthgroups USING btree (protein_id, orthgroup_id);


--
-- Name: si_proteins_speciesid; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_proteins_speciesid ON items.proteins USING btree (species_id);


--
-- Name: si_runs_genespr_combined_1; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_runs_genespr_combined_1 ON items.runs_genes_proteins USING btree (gene_id, run_id);


--
-- Name: si_runs_genespr_combined_2; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_runs_genespr_combined_2 ON items.runs_genes_proteins USING btree (protein_id, run_id);


--
-- Name: si_runs_orthgroups_combined1; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_runs_orthgroups_combined1 ON items.runs_orthgroups USING btree (run_id, orthgroup_id);

ALTER TABLE items.runs_orthgroups CLUSTER ON si_runs_orthgroups_combined1;


--
-- Name: si_runs_orthgroups_combined2; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_runs_orthgroups_combined2 ON items.runs_orthgroups USING btree (orthgroup_id, run_id);


--
-- Name: si_species_compactname; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_species_compactname ON items.species USING btree (compact_name);


--
-- Name: si_species_officialname; Type: INDEX; Schema: items; Owner: -
--

CREATE INDEX si_species_officialname ON items.species USING btree (official_name);


--
-- Name: pi_actions_temp_itemid_a; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX pi_actions_temp_itemid_a ON network.actions USING btree (item_id_a);

ALTER TABLE network.actions CLUSTER ON pi_actions_temp_itemid_a;


--
-- Name: pi_best_combined_orthgroup_id; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX pi_best_combined_orthgroup_id ON network.best_combined_scores_orthgroups USING btree (orthgroup_id);

ALTER TABLE network.best_combined_scores_orthgroups CLUSTER ON pi_best_combined_orthgroup_id;


--
-- Name: pi_best_combined_protein_id; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX pi_best_combined_protein_id ON network.best_combined_scores_proteins USING btree (protein_id);

ALTER TABLE network.best_combined_scores_proteins CLUSTER ON pi_best_combined_protein_id;


--
-- Name: pi_hierarchical_ogs_tr_score_id_eggnog_id_a_eggnog_id_b; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX pi_hierarchical_ogs_tr_score_id_eggnog_id_a_eggnog_id_b ON network.hierarchical_ogs_transfer_reports USING btree (score_id, eggnog_id_a, eggnog_id_b) WITH (fillfactor='100');

ALTER TABLE network.hierarchical_ogs_transfer_reports CLUSTER ON pi_hierarchical_ogs_tr_score_id_eggnog_id_a_eggnog_id_b;


--
-- Name: pi_node_links_node_id_a; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX pi_node_links_node_id_a ON network.node_node_links USING btree (node_id_a) WITH (fillfactor='100');

ALTER TABLE network.node_node_links CLUSTER ON pi_node_links_node_id_a;


--
-- Name: si_hierarchical_ogs_tr_eggnog_id_a_eggnog_id_b; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX si_hierarchical_ogs_tr_eggnog_id_a_eggnog_id_b ON network.hierarchical_ogs_transfer_reports USING btree (eggnog_id_a, eggnog_id_b) WITH (fillfactor='100');


--
-- Name: si_node_links_node_id_a_node_type_b_combined_score; Type: INDEX; Schema: network; Owner: -
--

CREATE INDEX si_node_links_node_id_a_node_type_b_combined_score ON network.node_node_links USING btree (node_id_a, node_type_b, combined_score) WITH (fillfactor='100');


--
-- PostgreSQL database dump complete
--

