-- Extract a small dump for testing
-- Species: Mus musculus (10090)

\copy (SELECT * FROM items.proteins WHERE species_id = 10090) TO 'proteins.mouse' BINARY;

CREATE TEMP VIEW node_node_links_tmp AS
    SELECT node_id_a,
           node_type_b,
           node_id_b,
           combined_score,
           evidence_scores
    FROM network.node_node_links AS links
    JOIN items.proteins AS proteins1 ON proteins1.protein_id = links.node_id_a
    JOIN items.proteins AS proteins2 ON proteins2.protein_id = links.node_id_b
    WHERE proteins1.species_id = 10090
        AND proteins2.species_id = 10090
        AND UPPER(proteins1.preferred_name) = 'CCR5'
        OR UPPER(proteins1.preferred_name) = 'CCL5'
        OR UPPER(proteins1.preferred_name) = 'IL10RA';
\copy (SELECT * FROM node_node_links_tmp) TO 'node_node_links.mouse' BINARY;

CREATE TEMP VIEW actions_sets_tmp AS
    SELECT item_id_a,
           item_id_b,
           mode,
           sources
    FROM network.actions_sets AS actions_sets
    JOIN items.proteins AS proteins1 ON proteins1.protein_id = actions_sets.item_id_a
    JOIN items.proteins AS proteins2 ON proteins2.protein_id = actions_sets.item_id_b
    WHERE proteins1.species_id = 10090
        AND proteins2.species_id = 10090
        AND UPPER(proteins1.preferred_name) = 'CCR5'
        OR UPPER(proteins1.preferred_name) = 'CCL5'
        OR UPPER(proteins1.preferred_name) = 'IL10RA';
\copy (SELECT * FROM actions_sets_tmp) TO 'actions_sets.mouse' BINARY;
